CREATE TABLE users (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    role INTEGER DEFAULT 1,
    encrypted_pwd VARCHAR(255) NOT NULL
);